Dev
AliaksandrZahorski/AliaksandrZahorski.github.io pull request #1
Opened 2017-03-17 16:40 UTC by AliaksandrZahorski

Базовые функции калькулятора:
сложение, вычитание, умножение, деление, целочисленное деление

2017-03-17 16:51 UTC, NikitaSedyx commented
hi, @AliaksandrZahorski could you make a separate folder for this task? thank you
basically code is fine, please try how it works without arguments, with `null` argument, strings like `ababa`

2017-03-17 17:38 UTC, AliaksandrZahorski commented
Sure. Now code in separate folder and new tests are added.

2017-03-17 18:25 UTC, NikitaSedyx requested changes

2017-03-17 18:25 UTC, NikitaSedyx commented on functions/index.html
> +	<title></title>
please use 2 spaces everywhere instead of 4

2017-03-17 18:25 UTC, NikitaSedyx commented on functions/index.html
> +</html>
empty line please at the EOF

2017-03-17 18:25 UTC, NikitaSedyx commented on functions/script.js
> +	var result = a + b;
the same for js

2017-03-17 18:25 UTC, NikitaSedyx commented on functions/script.js
> +	var result = a - b;
actually you could do `return a - b;`.  less code + same sense
the same for another functions.

2017-03-17 18:25 UTC, NikitaSedyx commented on functions/index.html
> +<body>
please make indentations for each nested tags

2017-03-17 19:11 UTC, AliaksandrZahorski commented on functions/index.html
> +	<title></title>
done

2017-03-17 19:11 UTC, AliaksandrZahorski commented on functions/index.html
> +</html>
add line

2017-03-17 19:12 UTC, AliaksandrZahorski commented on functions/script.js
> +	var result = a + b;
fulfilled

2017-03-17 19:13 UTC, AliaksandrZahorski commented on functions/index.html
> +<body>
performed

2017-03-17 19:15 UTC, AliaksandrZahorski commented
Thanks for the helpful comments!

2017-03-17 19:18 UTC, NikitaSedyx approved these changes

2017-03-18 06:35 UTC, NikitaSedyx commented on functions/script.js
> +  return (a - a % b) / b;
`%` sometimes returns result you don't want
please try `3.5 % 2`.
if I will pass float number in your function in can give me wrong result, please test it

2017-03-18 08:40 UTC, AliaksandrZahorski commented on functions/script.js
> +  return (a - a % b) / b;
More tests are added. Also new version of function "divT(a, b)" is added.
Looks like they both returns expected values.

2017-03-18 08:55 UTC, NikitaSedyx approved these changes
please fix comments and merge

2017-03-18 08:55 UTC, NikitaSedyx commented on functions/script.js
> +  if (isNaN(x)) {
this `if` doesn't make sense, Math.ceil(NaN) = NaN

2017-03-18 08:55 UTC, NikitaSedyx commented on functions/script.js
> +  return trunc(a/b);;
two semicolons?

2017-03-18 08:55 UTC, NikitaSedyx commented on functions/script.js
> +  return trunc(a/b);;
you could use parseInt :) it's safer than (/ - / %)

2017-03-18 09:41 UTC, merged