JS Training tasks 24.03
AliaksandrZahorski/AliaksandrZahorski.github.io pull request #2
Opened 2017-03-24 20:48 UTC by AliaksandrZahorski

2017-03-25 06:34 UTC, NikitaSedyx requested changes

2017-03-25 06:34 UTC, NikitaSedyx commented on html/index.html
> +    <figure>
it looks strange that's figure is outside main or section

2017-03-25 06:34 UTC, NikitaSedyx commented on html/index.html
> +    <main>
main tag defines the main content in your document, for me it's like a wrapper for everything except footer, header, nav

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +  return !!obj && obj.constructor === Array;
I prefer _#2

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +  if (b === undefined) {
only undefined, if b is null or string, or boolean?

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +function range(a, b) {
it gives wrong result with arguments (1, 5), (10, 15), (10, -5). when b is negative it will be infinite loop

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +  var result = new Array();
do you know difference between [] and new Array?

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +  result = obj.filter(function(e){
filter returns array
you create new array and initialize `result` with it, and after you override with another one

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +function compact(obj) {
`obj`? it's array

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +}
empty line please

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +function onlyUnique(value, index, self) {
why do you need this function in global scope?

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +function unique(obj) {
could you also implement `unique` via loop? thanks

2017-03-25 06:34 UTC, NikitaSedyx commented on array/script.js
> +  return arr.slice(0, -1 - len);;
`;;`?

2017-03-25 06:35 UTC, NikitaSedyx commented
in additional: you can't merge js task till there are mistakes in html tasks, and vice versa because you have 1 PR for 2 tasks

2017-03-25 10:08 UTC, AliaksandrZahorski commented on html/index.html
> +    <main>
fixed

2017-03-25 10:09 UTC, AliaksandrZahorski commented on html/index.html
> +    <figure>
fixed

2017-03-25 10:10 UTC, AliaksandrZahorski commented on array/script.js
> +  return !!obj && obj.constructor === Array;
fixed

2017-03-25 10:28 UTC, AliaksandrZahorski commented on array/script.js
> +function range(a, b) {
Fixed for (1,5) and (10,15). Will the [] array be a proper result for (10, -5)?

2017-03-25 10:32 UTC, AliaksandrZahorski commented on array/script.js
> +  if (b === undefined) {
null -> 0, string -> will try parse to Number, boolean -> 0 or 1
I just check number of arguments for range.

2017-03-25 10:33 UTC, AliaksandrZahorski commented on array/script.js
> +function compact(obj) {
fixed

2017-03-25 10:35 UTC, AliaksandrZahorski commented on array/script.js
> +  var result = new Array();
[] is a new runtime array. It's fast.
new Array() call the constructor "Array" and generate an object. Just for experiment.

2017-03-25 10:36 UTC, AliaksandrZahorski commented on array/script.js
> +  result = obj.filter(function(e){
fixed

2017-03-25 10:38 UTC, AliaksandrZahorski commented on array/script.js
> +function onlyUnique(value, index, self) {
Just for try another way. Want to see that not only anonimous functions can be used.

2017-03-25 10:47 UTC, AliaksandrZahorski commented on array/script.js
> +function unique(obj) {
Done. Second one is more slow.

2017-03-25 10:47 UTC, AliaksandrZahorski commented on array/script.js
> +}
fixed

2017-03-25 10:49 UTC, AliaksandrZahorski commented
Should I create an additional branch or just do two consecutive requests?

2017-03-25 11:10 UTC, NikitaSedyx commented on array/script.js
> +function range(a, b) {
yes

2017-03-25 11:18 UTC, NikitaSedyx requested changes

2017-03-25 11:18 UTC, NikitaSedyx commented on array/script.js
> +    for (var i = 0; i < arr.length; i++) {
nit: wrong indent

2017-03-25 11:18 UTC, NikitaSedyx commented on array/script.js
> +      var str = arr[i];
strange variable name, it's value

2017-03-25 11:18 UTC, NikitaSedyx commented on array/script.js
> +          continue;
I think it should be `break`

2017-03-25 11:18 UTC, NikitaSedyx commented on array/script.js
> +}
empty line

2017-03-25 11:18 UTC, NikitaSedyx commented on html/index.html
> +      <figure>
why is not `fugire` inside section or another content wrapper?

2017-03-25 11:18 UTC, NikitaSedyx commented on html/index.html
> +        <aside>
> The aside element defines some content aside from the content it is placed in (like a sidebar). The aside content should be related to the surrounding content.

2017-03-25 11:51 UTC, AliaksandrZahorski commented on array/script.js
> +    for (var i = 0; i < arr.length; i++) {
fixed

2017-03-25 11:51 UTC, AliaksandrZahorski commented on array/script.js
> +      var str = arr[i];
Changed to currentValue

2017-03-25 11:52 UTC, AliaksandrZahorski commented on array/script.js
> +          continue;
fixed

2017-03-25 11:52 UTC, AliaksandrZahorski commented on array/script.js
> +}
fixed

2017-03-25 11:54 UTC, AliaksandrZahorski commented on html/index.html
> +        <aside>
fixed

2017-03-25 11:55 UTC, AliaksandrZahorski commented on html/index.html
> +      <figure>
fixed

2017-03-25 12:14 UTC, NikitaSedyx requested changes

2017-03-25 12:14 UTC, NikitaSedyx commented on html/index.html
> +          <aside>
again aside shouldn't be inside article in your case

2017-03-25 12:14 UTC, NikitaSedyx commented on array/script.js
> +function excludeLast(arr, len = 0) {
`len = 0` is ES6

2017-03-25 12:14 UTC, NikitaSedyx commented on array/script.js
> +function excludeLast(arr, len = 0) {
`excludeLast([1, 2, 3], 1)` returns [1], but should return [1,2]

2017-03-25 12:14 UTC, NikitaSedyx commented on array/script.js
> +function last(obj) {
obj?

2017-03-25 12:14 UTC, NikitaSedyx commented on array/script.js
> +
nit: extra line

2017-03-25 12:14 UTC, NikitaSedyx commented on array/script.js
> +    for(var i = 0; i < arr.length; i++) {
again wrong indents

2017-03-25 14:04 UTC, AliaksandrZahorski commented on html/index.html
> +          <aside>
moved to <article>

2017-03-25 14:06 UTC, AliaksandrZahorski commented on array/script.js
> +    for(var i = 0; i < arr.length; i++) {
fixed one more times

2017-03-25 14:09 UTC, AliaksandrZahorski commented on array/script.js
> +
extra line are deleted

2017-03-25 14:10 UTC, AliaksandrZahorski commented on array/script.js
> +function last(obj) {
replaced to arr

2017-03-25 14:27 UTC, AliaksandrZahorski commented on array/script.js
> +function excludeLast(arr, len = 0) {
method is owerwritten

2017-03-25 19:47 UTC, NikitaSedyx requested changes

2017-03-25 19:47 UTC, NikitaSedyx commented on array/script.js
> +  var last = arr.splice(-len, len);
function was mutated :-1:

2017-03-25 19:47 UTC, NikitaSedyx commented on html/index.html
> +        <aside>
don't see fix

2017-03-25 20:02 UTC, AliaksandrZahorski commented on html/index.html
> +        <aside>
another try to fix

2017-03-25 20:08 UTC, AliaksandrZahorski commented on array/script.js
> +  var last = arr.splice(-len, len);
removed side effects

2017-03-26 11:25 UTC, NikitaSedyx requested changes

2017-03-26 11:25 UTC, NikitaSedyx commented on html/index.html
> +          <aside>
please look at picture https://www.w3schools.com/html/html5_semantic_elements.asp

2017-03-26 11:25 UTC, NikitaSedyx commented on array/script.js
> +  var last = newArray.splice(-len, len);
why do not use `slice` to exclude?
1 slice is faster than slice + splice

2017-03-26 11:25 UTC, NikitaSedyx commented on array/script.js
> +    return e;
nit: it can be one line

2017-03-26 11:25 UTC, NikitaSedyx commented on array/script.js
> +function excludeLast(arr, len) {
function works fine, but please think how to improve it

2017-03-26 13:58 UTC, AliaksandrZahorski commented on html/index.html
> +          <aside>
I saw this example.
Another fix done.

2017-03-26 14:01 UTC, AliaksandrZahorski commented on array/script.js
> +    return e;
fixed

2017-03-26 14:18 UTC, AliaksandrZahorski commented on array/script.js
> +function excludeLast(arr, len) {
fixed

2017-03-26 14:19 UTC, AliaksandrZahorski commented on array/script.js
> +  var last = newArray.splice(-len, len);
function is rewritten

2017-03-26 14:31 UTC, NikitaSedyx approved these changes

2017-03-26 17:23 UTC, merged